# Generated by Django 3.0.3 on 2020-04-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='default title', max_length=255),
            preserve_default=False,
        ),
    ]
